#! /usr/bin/python
# -*-coding:utf-8 -*-

from os import geteuid

from backend import update, transaction

if __name__ == "__main__":
	if geteuid() == 0:
		transaction.progress_label.set_text('Refreshing...')
		transaction.progress_bar.pulse()
		transaction.action_icon.set_from_file('/usr/share/icons/hicolor/24x24/status/refresh-cache.png')
		transaction.ProgressWindow.show_all()
		transaction.do_refresh()
		transaction.ProgressWindow.hide()
	update.main()
