#! /usr/bin/python
# -*-coding:utf-8-*-

from pamac import common, transaction

if not common.pid_file_exists():
	print('checking updates')
	common.write_pid_file()
	transaction.Refresh()
	transaction.TransactionDone()
	transaction.StopDaemon()
	common.rm_pid_file()
	print('check updates done')
